- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: 'yes'
    devstack: true
    disable_edx_services: true
    mongo_enable_journal: false
    EDXAPP_NO_PREREQ_INSTALL: 0
    COMMON_SSH_PASSWORD_AUTH: "yes"
    EDXAPP_LMS_BASE: 127.0.0.1:8000
    ECOMMERCE_ECOMMERCE_DOMAIN: "localhost:8002"
    ECOMMERCE_PARTNER_CODE: edx
    OTTO_MULTITENANT_SETUP_FROM_EMAIL: devstack-notifications@edx.org
    EDXAPP_OAUTH_ENFORCE_SECURE: false
    EDXAPP_LMS_BASE_SCHEME: http
    ECOMMERCE_DJANGO_SETTINGS_MODULE: "ecommerce.settings.devstack"
  roles:
    - common
    - vhost
    - edx_ansible
    - mysql
    - edxlocal
    - memcache
    - mongo
    - { role: 'rabbitmq', rabbitmq_ip: '127.0.0.1' }
    - edxapp
    - oraclejdk
    - elasticsearch
    - forum
    - ecommerce
    - ecomworker
    - programs
    - role: notifier
      NOTIFIER_DIGEST_TASK_INTERVAL: "5"
    - browsers
    - browsermob-proxy
    - local_dev
    - demo
    - oauth_client_setup
    - otto_multitenant_setup
